#!/bin/bash

if [ "${SETUP_AWSCLI_LOGIN}" == true ]
then
  if [ ! -e ~/.aws-login/config ]
  then
    echo "[START] awscli-login configuration"
    # make sure endpoint variable is set, if not set to CIT default
    if [[ -z "${ECP_ENDPOINT}" ]]
    then
      echo "[INFO] ECP_EMDPOINT environment variables not set, setting to default CIT endpoint"
      export ECP_ENDPOINT="https://shibidp.cit.cornell.edu/idp/profile/SAML2/SOAP/ECP"
    fi

    # create array of options that will be used to write aws-login config file
    config_array=( "[default]" "ecp_endpoint_url = ${ECP_ENDPOINT}" "username = ${NETID}" "factor = ${DUO_FACTOR}" )

    # configure aws cli to use awscli-login
    aws configure set plugins.login awscli_login >/dev/null

    # write aws-login config file
    printf "%s\n" "${config_array[@]}" > ~/.aws-login/config
    echo "[FINISH] awscli-login configuration successful"
  else
    echo "[INFO] skipping awscli-login configuration - config found"
  fi
else
  echo "[INFO] skipping awscli-login configuration"
fi

# install fx (via node/npm)
if [ "${SETUP_FX}" == true ]
then
  echo "[START] fx/nodejs/npm installation"
  curl -sL https://deb.nodesource.com/setup_11.x | bash - &> /dev/null
  apt-get install -qy nodejs &> /dev/null
  npm i -g fx &> /dev/null
  echo "[FINISH] fx/nodejs/npm installation successful"
else
  echo "[INFO] skipping fx/nodejs/npm installation"
fi

# install oh-my-zsh, zsh-completions/zsh-autosuggestions plugins, and set shell to zsh
if [ "${SETUP_OHMYZSH}" == true ]
then
  echo "[START] oh-my-zsh setup/configuration"
  curl -Lo install.sh https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
  sh ./install.sh --unattended
  chsh -s /bin/zsh
  rm ./install.sh
  /bin/zsh
  git clone --quiet https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  git clone --quiet https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions
  sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="refined"/g' ~/.zshrc
  sed -i 's/# HYPHEN_INSENSITIVE=/HYPHEN_INSENSITIVE=/g' ~/.zshrc
  sed -i 's/plugins=(git)/plugins=(git aws zsh-completions zsh-autosuggestions)/g' ~/.zshrc
  sed -i '/plugins=(git)/a autoload -U compinit && compinit' ~/.zshrc
  echo "[FINISH] oh-my-zsh setup/configuration successful"
else
  echo "[INFO] skipping oh-my-zsh setup/configuration"
  /bin/bash
fi

# install terraform and enable terraform autocomplete
if [ "${SETUP_TERRAFORM}" == true ]
then
  echo "[START] terraform and terraform autocomplete configuration"
  wget "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_darwin_amd64.zip"
  unzip "./terraform_${TERRAFORM_VERSION}_darwin_amd64.zip"
  mv ./terraform /usr/local/bin/terraform
  terraform -install-autocomplete
  echo "[FINISH] terraform and terraform configuration successful"
else
  echo "[INFO] skipping terraform and terraform configuration"
fi
