#!/bin/bash

if [[ -z "${ECP_ENDPOINT}" ]] || [[ -z "${NETID}" ]]
then
  echo "Environment variables not set, aborting awscli-login config setup"
  exit 128
fi

config_array=( "[default]" "ecp_endpoint_url = ${ECP_ENDPOINT}" "username = ${NETID}" "factor = push" )

aws configure set plugins.login awscli_login

if [ ! -e ~/.aws-login/config ]
then
  printf "%s\n" "${config_array[@]}" > ~/.aws-login/config
  echo "Default awscli-login config written successfully"
else
  echo "Skipping setup, awscli-login config found"
fi

# if [ -n "${REPO_URL}" ]
# then
#   REPO_DIR="${REPO_URL##*/}"
#   REPO_DIR="${REPO_DIR%.*}"
#   if [ ! -d "${REPO_DIR}" ]; then
#     git clone "${REPO_URL}"
#     echo "Successfully cloned repo into /mounted-home/${REPO_DIR} folder"
#   fi
# fi
